version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:16.10.0
    working_directory: ~/test # https://circleci.com/docs/configuration-reference/?query=CIRCLE_WORKING_DIRECTORY
    steps:
      - checkout
      - run:
          name: Run access
          command: node access.js
      - run:
          name: Run accessSync
          command: node accessSync.js
      - run:
          name: Run appendFile
          command: node appendFile.js

workflows:
  workflow-name:
    jobs:
      - build