pipeline {
    agent {
        docker {
            image 'node:16.10.0'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'node access.js'
            }
        }
    }
}