pipeline {
    agent {
        docker {
            image 'node:6-alpine'
            args '-p 3000:3000'
        }
    }
    stages {
        stage("Tear Down"){
            steps {
                deleteDir()
            }
        }
        stage('Clone Repo') {
            steps {
                sh 'git clone https://github.com/ramchamselenium/js-fs.git'
            }
        }
        stage("Build"){
            steps {
                dir("js-fs") {
                    sh "node access.js"
                }
            }
        }
    }
}