pipeline {
  agent any
  tools {nodejs "nodejs"}
    stages {
        stage("Tear Down"){
            steps {
                deleteDir()
            }
        }
        stage('Clone Repo') {
            steps {
                sh 'git clone https://github.com/ramchamselenium/js-fs.git'
            }
        }
        stage("Build"){
            steps {
                dir("js-fs") {
                    sh "node access.js"
                }
            }
        }
    }
}